FROM library/python:3-alpine

MAINTAINER USITINT <uav-int@usit.uio.no>

# Proxy for updates during build
ENV http_proxy="http://updateproxy.uio.no:3128"
ENV https_proxy="https://updateproxy.uio.no:3128"

WORKDIR /usr/src/evalg

# deps
ADD . /usr/src/evalg

# Install build-deps, then install/build deps
RUN set -ex \
    && apk add --no-cache --virtual .evalg-build-deps \
            gcc \
            make \
            libc-dev \
            musl-dev \
            linux-headers \
            postgresql-dev \
    && pip3 install -U pip \
    && pip3 install -r /usr/src/evalg/requirements-test.txt \
    && pip3 install -r /usr/src/evalg/requirements.txt \
    && apk del .evalg-build-deps \
    && apk add --no-cache \
            git \
            bash \
            postgresql-dev

RUN pip3 install --editable /usr/src/evalg

# Reset proxy -- we don't want the build image to have these
ENV http_proxy=""
ENV https_proxy=""
