FROM library/python:3-alpine

MAINTAINER USITINT <uav-int@usit.uio.no>

WORKDIR /usr/src/evalg

# Add dependencies
ADD requirements-test.txt /usr/src/evalg
ADD requirements.txt /usr/src/evalg

# Install build-deps, then install/build deps
RUN set -ex \
    && apk add --no-cache --virtual .evalg-build-deps \
            gcc \
            make \
            libc-dev \
            musl-dev \
            linux-headers \
    && apk add --no-cache --virtual .evalg-deps \
            git \
            bash \
            postgresql-dev \
    && pip3 install -U pip \
    && pip3 install -r /usr/src/evalg/requirements-test.txt \
    && pip3 install -r /usr/src/evalg/requirements.txt \
    && apk del .evalg-build-deps

# Install app
ADD . /usr/src/evalg
RUN pip3 install --editable /usr/src/evalg