FROM library/python:3-alpine

MAINTAINER USITINT <uav-int@usit.uio.no>

# Proxy for updates during build
ENV http_proxy="http://updateproxy.uio.no:3128"
ENV https_proxy="https://updateproxy.uio.no:3128"

WORKDIR /usr/src/evalg

# deps
ADD . /usr/src/evalg

# Install build-deps, then install/build deps
RUN set -ex \
    && apk add --no-cache --virtual .evalg-build-deps \
            gcc \
            make \
            libc-dev \
            musl-dev \
            linux-headers \
            postgresql-dev \
    && apk add --no-cache --virtual .evalg-deps \
            git \
            bash \
    && pip3 install -U pip \
    && pip3 install -r /usr/src/evalg/requirements.txt \
    && apk del .evalg-build-deps

RUN pip3 install /usr/src/evalg

# Reset proxy -- we don't want the build image to have these
ENV http_proxy=""
ENV https_proxy=""

# Setup evalg
EXPOSE 8000

# ENV FLASK_APP="evalg.wsgi"
# RUN flask db migrate ?

CMD ["gunicorn", "-b", "0.0.0.0:8000", "evalg.wsgi"]
