import generalText from './general.nb';

const { election, ...restGeneral} = generalText;

const electionAdmin = {
  votesOutsideCensus: 'Stemmer utenfor manntallet',
  multipleTimes: 'Flere tider',
  manageElections: 'Administrer valg',
  manageableElections: 'Valg du kan administrere',
  createNewElection: 'Opprett nytt valg',
  addCandidate: 'Legg til kandidat',
  editCandidate: 'Endre kandidat',
  deleteCandidate: 'Slett kandidat',
  candidateNamePlaceHolder: 'Navn på kandidat',
  coCandidateNamePlaceHolder: 'Navn på medkandidat',
  closed: 'Stengt',
  published: 'Publisert',
  draft: 'Utkast',
  multipleStatuses: 'Flere verdier',
  newCoCandidate: 'Ny medkandidat',
  candidateUrl: 'https://example.org',
  remove: 'Fjern',
  editBoardLeaderCandidate: 'Endre kandidat og medkandidater',
  addPrefTeamCandidate: 'Legg til kandidat og medkandidater',
  noCandidatesDefined: 'Det er ingen kandidater i listen.',
  noCandidatesFound: 'Ingen kandidater tilfredstiller søkekriteriene.',
  electionInfo: 'Valginformasjon',
  electionType: 'Valgordning',
  electionStatus: 'Valgstatus',
  selectType: 'Velg valgordning',
  selectLevel: 'Valg av',
  selectParish: 'Valgkrets',
  voterSettings: 'Velgergrupper og kandidatinnstillinger',
  activeElectionsHeader: 'Hvilke grupper skal representeres og hvor mange kandidater skal velges fra hver av gruppene?',
  group: 'Gruppe',
  nrOfCandidates: 'Antall faste representanter',
  nrOfCoCandidates: 'Antall vararepresentanter',
  votingPeriod: 'Stemmeperiode',
  votingPeriodSubHeader: 'I hvilken tidsperiode skal valget være åpent for velgerne?',
  voterGroup: 'Velgergruppe',
  singleVotingPeriod: 'Felles stemmeperiode',
  multipleVotingPeriods: 'Invidiuelle stemmeperioder',
  voterInfo: 'Informasjon til velgerne',
  voterInfoFormDesc: 'Informasjonen som angis her vil være synlig på forsiden hos velgerne.',
  mandatePeriod: 'Mandatperiode',
  mandatePeriodShared: 'Felles mandatperiode for alle velgergrupper',
  mandatePeriodMultiple: 'Individuell mandatperiode for velgergrupper',
  voterContactInfo: 'Kontaktpunkt for velgerne',
  voterContactInfoShared: 'Felles kontaktinformasjon for alle velgergrupper',
  voterContactInfoMultiple: 'Individuell kontaktinformasjon for velgergrupper',
  voterInfoUrl: 'Lenke til mer informasjon om valget',
  voterInfoUrlShared: 'Felles nettside',
  voterInfoUrlMultiple: 'Individuelle nettsider for velgergrupper',
  adminRoles: 'Administrative roller',
  adminRolesDesc: 'Rollene angir hvem som har rettigheter i forbindelse med valget.',
  electionAdmins: 'Valgansvarlige',
  electionAdminsDesc: 'Kan endre innstillinger og informasjon for valget, telle stemmer og delegere tilganger.',
  electionOpens: 'Valget åpner',
  electionCloses: 'Valget stenger',
  goTo: 'Gå til',
  settings: 'valginnstillinger',
  status: 'valgstatus',
  noManageableElections: 'Det er for øyeblikket ingen valg hvor du er registrert som administrator.',
  valueNotSet: 'ikke satt',
  noActiveElections: 'Det er for øyeblikket ingen valg som er satt som aktive.',
  prefTeamHeader: 'Her kan du legge til og administrere kandidater og medkandidater som stiller til valg.',
  candidateCounter: 'Har {{count}} av {{minCount}} kandidater',
  publish: 'Publiser',
  publishElection: 'Publiser valget',
  publishElectionModalInfo: 'Valget vil være synlig for velgerne og åpner automatisk til angitt tidspunkt.',
  unpublish: 'Avpubliser',
  unpublishElection: 'Avpubliser valget',
  unpublishElectionModalInfo: 'Valget vil ikke åpne automatisk.',
  announceElectionHeader: 'Synliggjør valget på forsiden',
  announceElectionConfirm: 'Synliggjør valget',
  announceElectionInfoOne: 'Valget og stemmeperioden for valget vil bli synlig på forsiden hos velgerne.',
  announceElectionInfoTwo: 'Merk at valget ikke kan starte før det oppfyller minimumskravene og publisering er godkjent av valgansvarlig.',
  announceElectionReadMore: 'Les mer om synliggjøring av valget',
  unannounceElectionHeader: 'Fjern valget fra forsiden',
  unannounceElectionConfirm: 'Fjern fra forsiden',
  unannounceElectionInfoOne: 'Valget og stemmeperioden for valget blir usynlig på forsiden hos velgerne.',
  unannounceElectionInfoTwo: 'Du vil kunne gjøre valget synlig igjen senere hvis du ønsker det.',
  electionNotStarted: 'Valget har ikke startet.',
  electionKey: 'Valgnøkkel',
  electionKeyMissing: 'En valgnøkkel er nødvendig for å telle opp stemmene.',
  electionKeyExists: 'En valgnøkkel eksisterer for dette valget.',
  electionKeyCreate: 'Lag nøkkel',
  electionKeySave: 'Lagre nøkkel',
  electionKeyStatusKeepItSafe: 'Sørg for at nøkkelen er lagret et sikkert sted. Uten nøkkelen kan ikke stemmene telles opp.',
  electionKeyStatusCanReplace: 'Frem til valget har startet vil du fortsatt ha mulighet til å lage en ny nøkkel som erstatter den gamle.',
  electionKeyReadMore: 'Les mer om nøkkelhåndtering',
  statusDraftNotReady: 'Valget oppfyller ikke minimumskravene',
  statusDraftReady: 'Valget oppfyller nå minimumskravene for å kunne gjennomføres',
  statusCanAnnounce: 'Du kan gjøre stemmeperioden for valget synlig for velgerne',
  statusDoAnnounce: 'Gjør synlig',
  statusIsAnnounced: 'Stemmeperioden for valget er synlig på forsiden hos velgerne',
  statusDoUnannounce: 'Fjern fra forsiden',
  statusThisIsMissing: 'Dette mangler',
  statusOpensAutomatically: "Valget er publisert og vil starte automatisk til angitt tidspunkt.",
  blockerUnknown: 'Noe uventet er galt',
  blockerMissingKey: 'Opptellingsnøkkel',
  blockerStartBeforeEnd: 'Starttid må være før sluttid',
  adminUser: 'Enkeltbrukere',
  adminGroup: 'Grupper',
};

const prefElec = {
  candPageDesc: 'Her legger du til kandidater som stiller for de ulike velgergruppene.<0></0>' +
                'Valget må ha minimum like mange kandidater per gruppe som angitt under <1>valginnstillinger</1>.',
};

const formErrors = {
  invalidDates: 'Starttid må være tidligere enn sluttid.',
  invalidEmail: 'Ugyldig epostadresse.',
  invalidUrl: 'Ugyldig url.'
};

const census = {
  censusPageDesc: 'Her kan du opprette og administrere manntall.',
  uploadCensusFile: 'Last opp manntallsfil',
  group: 'Gruppe',
  person: 'Person',
  addPerson: 'Legg til person',
  addPersons: 'Legg til personer i',
  deleteCensus: 'Slett manntall',
  addPersonModalHeader: 'Legg til personer i manntallet',
  addTo: 'Legg til',
  addPersonInputPlaceholder: 'Skriv inn brukernavn, navn eller fødselsnummer',
  addPersonHelpText: 'Du kan også legge inn flere personer separert med komma',
  deletePersonModalTitle: 'Bekreft sletting',
  deletePersonModalText: 'Er du sikker på at du vil slette {{personName}} fra «{{pollbookName}}»?'
};


export default {
  election: Object.assign({}, {...election, ...electionAdmin}),
  ...restGeneral,
  i18n: {
    __typename: 'AppTexts',
    datePlaceHolder: 'dd.mm.åååå',
    timePlaceHolder: 'tt:mm'
  },
  formErrors,
  prefElec,
  census
}
