export default {
  general: {
    __typename: 'AppTexts',
    yes: 'Yes',
    no: 'No',
    of: 'of',
    title: 'eValg',
    group: 'Group',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    name: 'Name',
    edit: 'edit',
    all: 'All',
    logout: 'Log out',
    ok: 'OK',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    choose: "Choose",
    close: 'Close',
    copy: 'Copy',
    at: "at",
    to: "to",
    select: 'Select',
    webpage: 'Nettside',
    contactInfo: 'Contact info',
    email: 'Email',
    remove: 'Remove',
    required: 'Required',
    menu: 'Menu',
    add: 'Add'
  },
  election: {
    __typename: 'AppTexts',
    election: 'Election',
    elections: 'Elections',
    opens: 'Opens',
    closes: 'Closes',
    status: 'Status',
    electionStatus: 'Election status',
    census: 'Census',
    censuses: 'Censuses',
    electionInfo: 'Election information',
    candidate: 'Candidate',
    candidates: 'Candidates',
    coCandidate: 'Co-candidate',
    coCandidates: 'Co-candidates',
    mandatePeriod: 'Mandate period',
    fromDate: 'From date',
    toDate: 'To date',
    contactForElectors: 'Contact point for electors',
    contactForElectorsPlaceholder: 'E-mail address or webpage',
    linkToElection: 'Link to more information about the election',
    linkToElectionPlaceholder: 'Webpage for the election',
    candidatesShort: 'candidates',
    coCandidatesShort: 'co-candidates',
    hasGenderQuota: 'Election uses gender quotas',
    quotas: 'Quotas',
    valueNotSet: 'not set',
    votes: 'Votes',
  },
  electionStatus: {
    __typename: 'AppTexts',
    draft: 'Draft',
    announced: 'Draft (announced)',
    published: 'Ready',
    closed: 'Closed',
    ongoing: 'Ongoing',
    multipleStatuses: 'Multiple Values',
    ongoingElections: 'Ongoing elections',
    upcomingElections: 'Upcoming elections',
    closedElections: 'Closed elections'
  }
}
