export default {
  general: {
    __typename: 'AppTexts',
    yes: 'Ja',
    no: 'Nei',
    of: 'av',
    title: 'eValg',
    group: 'Gruppe',
    gender: 'Kjønn',
    male: 'Mann',
    female: 'Kvinne',
    name: 'Navn',
    edit: 'endre',
    all: 'Alle',
    logout: 'Logg ut',
    ok: 'OK',
    save: 'Lagre',
    cancel: 'Avbryt',
    delete: 'Slett',
    choose: "Velg",
    close: 'Lukk',
    copy: 'Kopiér',
    at: "ved",
    to: "til",
    select: 'Velg',
    webpage: 'Nettadresse',
    contactInfo: 'Kontaktinfo',
    email: 'Epost',
    remove: 'Fjern',
    required: 'Påkrevd',
    menu: 'Meny',
    add: 'Legg til'
  },
  election: {
    __typename: 'AppTexts',
    election: 'Valg',
    elections: 'Valg',
    opens: 'Åpnes',
    closes: 'Avsluttes',
    status: 'Status',
    electionStatus: 'Valgstatus',
    census: 'Manntall',
    censuses: 'Manntall',
    electionInfo: 'Valginformasjon',
    candidate: 'Kandidat',
    candidates: 'Kandidater',
    coCandidate: 'Medkandidat',
    coCandidates: 'Medkandidater',
    mandatePeriod: 'Mandatperiode',
    fromDate: 'Fra dato',
    toDate: 'Til Dato',
    contactForElectors: 'Kontaktpunkt for velgerne',
    contactForElectorsPlaceholder: 'E-postadresse eller nettside',
    linkToElection: 'Lenke til mer informasjon om valget',
    linkToElectionPlaceholder: 'Nettside for valget',
    candidatesShort: 'faste',
    coCandidatesShort: 'vara',
    hasGenderQuota: 'Valget har kjønnskvotering',
    quotas: 'Kvotering',
    votes: 'Stemmer',
    valueNotSet: 'ikke satt',
  },
  electionStatus: {
    __typename: 'AppTexts',
    draft: 'Utkast',
    announced: 'Utkast (annonsert)',
    published: 'Klart',
    closed: 'Stengt',
    ongoing: 'Pågår',
    multipleStatuses: 'Flere verdier',
    ongoingElections: 'Pågående valg',
    upcomingElections: 'Kommende valg',
    closedElections: 'Avsluttede valg'
  }
}
